version: '3.8'

services:
  test_db:
    image: postgres:15-alpine
    container_name: pg_index_test
    environment:
      POSTGRES_DB: testing_perf
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
