[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pg_idx_manager"
version = "0.1.1"
description = "A lightweight, framework-agnostic developer linter and cleanup tool for PostgreSQL indexes."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Pierpaolo", email = "pierpaoloiannelli18@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Database :: Database Engines/Servers",
]
dependencies = [
    "psycopg2-binary>=2.9.0"
]

[tool.setuptools]
packages = ["pg_idx_manager"] 
