import logging
import sys
from sqlalchemy import create_engine, Column, Integer, String, Numeric, event
from sqlalchemy.orm import declarative_base, sessionmaker
# FIX: Using the correct, abbreviated directory package name
from pg_idx_manager import IndexManagerCore

# 1. Database Connection Configuration
DATABASE_URL = "postgresql+psycopg2://tester:supersecretpassword@localhost:5432/testing_perf"
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# 2. ORM Model Mapping
class Order(Base):
    __tablename__ = "orders"
    id = Column(Integer, primary_key=True, index=True)
    customer_name = Column(String)
    status = Column(String)
    amount = Column(Numeric)

# 3. GLOBAL ORM AUDIT HOOK (Safely processes parameterized queries)
@event.listens_for(engine, "before_cursor_execute")
def receive_before_cursor_execute(conn, cursor, statement, parameters, context, executing_many):
    """
    Globally intercepts any SQL query generated by SQLAlchemy before it hits the wire,
    forwarding bind parameters to the core engine to prevent placeholder syntax errors.
    """
    # Avoid recursion loops and ignore internal catalog setup queries
    clean_statement = statement.strip().upper()
    if clean_statement.startswith("EXPLAIN") or "PG_CATALOG" in clean_statement:
        return

    try:
        # Extract the underlying raw psycopg2 connection structure from the SQLAlchemy connection
        raw_conn = conn.connection.dbapi_connection
        
        # Initialize the core engine
        manager = IndexManagerCore(raw_conn, min_table_rows=0)
        
        # We pass both the statement string AND the runtime parameters dictionary
        anomalies, execution_time = manager.analyze_query(statement, parameters)
        
        # Print neutral telemetry metrics report to the console
        print("\n" + "="*50)
        print(f"📊 AUTOMATIC ORM QUERY TELEMETRY")
        print(f"   Execution Time: {execution_time} ms")
        print("="*50)
        print(f"   SQL: {statement.strip()}")
        if parameters:
            print(f"   Parameters: {parameters}")
        print("-"*50)
        
        if not anomalies:
            print(" 🎯 Scan Type: INDEX SCAN (or Index-Only Scan)")
            print("   Status: Optimized execution.")
        else:
            print(" ℹ️  Scan Type: SEQUENTIAL SCAN (Full Table Scan)")
            for am in anomalies:
                print(f"   Target Table: '{am['table']}'")
                if am.get('filter'):
                    print(f"   Applied filter: {am['filter']}")
        print("="*50 + "\n")
        
    except Exception as e:
        # Fallback to prevent internal logging crashes from blocking the application main thread execution
        logging.warning(f"Could not audit ORM query safely: {e}")


if __name__ == "__main__":
    # Create target relation schemas if they do not exist in the database instance
    Base.metadata.create_all(engine)
    
    db_session = SessionLocal()
    
    try:
        print("🕵️ Running ORM queries... watch the console telemetry hooks!")
        
        # --- TEST QUERY 1: Forces a Sequential Scan (customer_name field lacks a database index) ---
        print("\n[Executing ORM Query for customer_name...]")
        user_order = db_session.query(Order).filter(Order.customer_name == "pierpaolo").first()
        
        # --- TEST QUERY 2: Leverages an Index Scan (ID is a primary key bound to an implicit database index) ---
        print("\n[Executing ORM Query for primary key ID...]")
        id_order = db_session.query(Order).filter(Order.id == 1).first()

    finally:
        db_session.close()
